apiVersion: v1
kind: Secret
metadata:
  name: pr-db-credentials
  namespace: purchase-requisition
  labels:
    app.kubernetes.io/name: purchase-requisition
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: pr_user
  password: XU3Fx_Ea7zTy6yWW7BfAl1uzz2Z3UTORhfQgHKWfYrA
