apiVersion: v1
kind: Secret
metadata:
  name: pr-app-secret
  namespace: purchase-requisition
  labels:
    app.kubernetes.io/name: purchase-requisition
type: Opaque
stringData:
  # CloudNativePG service: pr-db-rw.purchase-requisition.svc (read-write primary)
  DATABASE_URL: "postgresql+psycopg://pr_user:XU3Fx_Ea7zTy6yWW7BfAl1uzz2Z3UTORhfQgHKWfYrA@pr-db-rw.purchase-requisition.svc:5432/purchase_requisition"
  SECRET_KEY: "a705c11289c31b610ba4fbe735838837c22d2a22829d05d29d98bf6fe46b34d2"
  # SMTP credentials (uncomment when ready)
  # SMTP_USER: ""
  # SMTP_PASS: ""
