"""initial schema

Revision ID: f8525c2d7463
Revises: 
Create Date: 2026-02-22 00:32:28.596046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8525c2d7463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requester_email', sa.String(length=200), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('need_by_date', sa.Date(), nullable=False),
    sa.Column('purchase_type', sa.String(length=20), nullable=False),
    sa.Column('is_outage', sa.Boolean(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('cost_code', sa.String(length=12), nullable=False),
    sa.Column('ea_number', sa.String(length=50), nullable=True),
    sa.Column('is_quote_attached', sa.Boolean(), nullable=False),
    sa.Column('manager_approval_received', sa.Boolean(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_pr_number'), ['pr_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_requester_email'), ['requester_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requisitions_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisition_items')
    op.drop_table('comments')
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_requester_email'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisitions_pr_number'))

    op.drop_table('purchase_requisitions')
    # ### end Alembic commands ###
