buyers:
  - email: diane.christensen@capitolaggregates.com
    name: Diane Christensen
    department: Purchasing

  - email: patrick.mcmahan@capitolaggregates.com
    name: Patrick McMahan
    department: Purchasing

  - email: michael.castillo@capitolaggregates.com
    name: Michael Castillo
    department: Storing

  - email: daniel.wyatt@capitolaggregates.com
    name: Daniel Wyatt
    department: Storing

  - email: jose.cedeno@capitolaggregates.com
    name: Jose Cedeno
    department: Maintenance
