apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: docker-registry
  labels:
    app.kubernetes.io/name: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
